language: csharp
solution: "./JwtWebApiAuthorization.sln"
install:
- travis_retry nuget restore -source "https://www.nuget.org/api/v2" ./JwtWebApiAuthorization.sln
script:
- xbuild ./JwtWebApiAuthorization.sln

-mono ./packages/NUnit.ConsoleRunner*/tools/nunit3-console.exe ./JwtWebApiAuthorization.Testing/bin/Debug/JwtWebApiAuthorization.Testing.dll