language: csharp
solution: ./JwtWebApiAuthorization.sln
 
install:
  - sudo apt-get install nunit-console
  - nuget restore ./JwtWebApiAuthorization.sln
 
script:
  - xbuild ./JwtWebApiAuthorization.sln.sln
  - nunit-console ./JwtWebApiAuthorization.Testing/bin/Debug/JwtWebApiAuthorization.Testing.dll