language: csharp
solution: JwtWebApiAuthorization.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore MTAServiceStatus.sln
after_script:
- nunit-console JwtWebApiAuthorization.Testing/bin/Debug/JwtWebApiAuthorization.Testing.dll