language: csharp
script:
  - xbuild /p:Configuration=Debug JwtWebApiAuthorization.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore JwtWebApiAuthorization.sln
after_script:
  - nunit-console JwtWebApiAuthorization.Testing/bin/Debug/JwtWebApiAuthorization.Testing.dll